# Generated by Django 3.0.2 on 2020-05-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_good', models.CharField(max_length=50)),
                ('price_good', models.IntegerField()),
                ('descripption_good', models.TextField(max_length=1000)),
                ('date_published_good', models.DateTimeField(auto_now_add=True)),
                ('image_good', models.ImageField(upload_to='images_goods/')),
            ],
        ),
    ]
