# Generated by Django 3.0.2 on 2020-05-25 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodityitem',
            old_name='descripption_good',
            new_name='description_good',
        ),
    ]
