# Generated by Django 3.0.2 on 2020-05-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0003_auto_20200525_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodityitem',
            name='image_good_galery_1',
            field=models.ImageField(default='default.jpg', upload_to='images_goods/gallery/'),
        ),
        migrations.AddField(
            model_name='commodityitem',
            name='image_good_galery_2',
            field=models.ImageField(default='default.jpg', upload_to='images_goods/gallery/'),
        ),
        migrations.AddField(
            model_name='commodityitem',
            name='image_good_galery_3',
            field=models.ImageField(default='default.jpg', upload_to='images_goods/gallery/'),
        ),
        migrations.AddField(
            model_name='commodityitem',
            name='image_good_galery_4',
            field=models.ImageField(default='default.jpg', upload_to='images_goods/gallery/'),
        ),
        migrations.AddField(
            model_name='commodityitem',
            name='image_good_galery_5',
            field=models.ImageField(default='default.jpg', upload_to='images_goods/gallery/'),
        ),
        migrations.AddField(
            model_name='commodityitem',
            name='image_good_galery_6',
            field=models.ImageField(default='default.jpg', upload_to='images_goods/gallery/'),
        ),
        migrations.AddField(
            model_name='commodityitem',
            name='image_good_galery_7',
            field=models.ImageField(default='default.jpg', upload_to='images_goods/gallery/'),
        ),
    ]
