# Generated by Django 3.0.7 on 2020-07-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0004_auto_20200525_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodityitem',
            name='image_good',
            field=models.FileField(upload_to='images_goods/'),
        ),
        migrations.AlterField(
            model_name='commodityitem',
            name='image_good_galery_1',
            field=models.FileField(upload_to='images_goods'),
        ),
        migrations.AlterField(
            model_name='commodityitem',
            name='image_good_galery_2',
            field=models.FileField(upload_to='images_goods/'),
        ),
        migrations.AlterField(
            model_name='commodityitem',
            name='image_good_galery_3',
            field=models.FileField(upload_to='images_goods/'),
        ),
        migrations.AlterField(
            model_name='commodityitem',
            name='image_good_galery_4',
            field=models.FileField(upload_to='images_goods/'),
        ),
        migrations.AlterField(
            model_name='commodityitem',
            name='image_good_galery_5',
            field=models.FileField(upload_to='images_goods/'),
        ),
        migrations.AlterField(
            model_name='commodityitem',
            name='image_good_galery_6',
            field=models.FileField(upload_to='images_goods/'),
        ),
        migrations.AlterField(
            model_name='commodityitem',
            name='image_good_galery_7',
            field=models.FileField(upload_to='images_goods/gallery'),
        ),
    ]
