# Generated by Django 3.0.2 on 2020-05-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_post', models.CharField(max_length=120)),
                ('description_post', models.TextField(max_length=400)),
                ('date_time_post', models.DateTimeField()),
                ('image_post', models.ImageField(upload_to='image_folder/')),
            ],
        ),
    ]
