# Generated by Django 3.0.2 on 2020-05-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostNews',
            new_name='PostNew',
        ),
    ]
