# Generated by Django 2.2.7 on 2020-07-08 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200619_1754'),
        ('news', '0004_auto_20200706_0956'),
    ]

    operations = [
    ]
