# Generated by Django 2.2.7 on 2020-07-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_merge_20200708_1858'),
        ('news', '0005_merge_20200715_1454'),
    ]

    operations = [
    ]
