# Generated by Django 3.0.7 on 2020-07-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_blog_post', models.CharField(max_length=120)),
                ('description_blog_post', models.TextField(max_length=400)),
                ('date_time_blog_post', models.DateTimeField()),
                ('label_blog_post', models.CharField(choices=[('UA', 'Ukraine'), ('RU', 'Russia'), ('PL', 'Poland'), ('BE', 'Belarus'), ('SK', 'Slovakia')], default='1', max_length=5)),
                ('image_blog_post', models.FileField(upload_to='blog_folder/')),
            ],
        ),
    ]
