# Generated by Django 3.0.7 on 2020-07-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='description_blog_post',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='label_blog_post',
            field=models.CharField(choices=[('Ukraine', 'UA'), ('Russia', 'RU'), ('Poland', 'PL'), ('Belarus', 'BE'), ('Slovakia', 'SK')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='name_blog_post',
            field=models.CharField(max_length=20),
        ),
    ]
