# Generated by Django 3.0.7 on 2020-07-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleFood', models.CharField(max_length=30)),
                ('textFood', models.TextField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('imageFood', models.ImageField(upload_to='FoodImages')),
            ],
        ),
    ]
