# Generated by Django 3.0.7 on 2020-07-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='date_published',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='imageFood',
            field=models.FileField(upload_to='FoodImages'),
        ),
    ]
