# Generated by Django 2.2.7 on 2020-07-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20200708_1859'),
        ('food', '0002_auto_20200715_1752'),
    ]

    operations = [
    ]
